databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"
envs:
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "0"
  - key: DJANGO_ALLOWED_HOST
    scope: RUN_AND_BUILD_TIME
    value: .ondigitalocean.app
  - key: DJANGO_SUPERUSER_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: hello@20202002karem.com
  - key: DJANGO_SUPERUSER_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: kareem
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:JFxpSsv8nv4BZoRNSJ2un+/xelusxlDw:usJzMvNkfs5znbOkcURgIuO1hIYYIQ==]
  - key: DJANGO_SUPERUSER_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:Xv1vF5dg1j6J5byozZF2gLgIL4yJNBAi:4vkUu90O3x0XvNrgq7MUElvRoQ==]
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:WdSr7DHwEv6Al1mAZ/h6ocf6VhA8GFSG:XJip6OYIa+JnxBgGR+wk21/kJQ==]
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:vOvUmh0DOJe2k1vbT+W1sWjMIp+cAeHR:nBfVIVfmQAIq2y0kxkcDr4Ar9HY=]
  - key: AWS_STORAGE_BUCKET_NAME
    scope: RUN_AND_BUILD_TIME
    value: trydjango3
ingress:
  rules:
    - component:
        name: try-django-3-2
      match:
        path:
          prefix: /
jobs:
  - environment_slug: python
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    github:
      branch: production-3
      deploy_on_push: true
      repo: 20202002karem/first-project
    instance_count: 1
    instance_size_slug: basic-xxs
    kind: PRE_DEPLOY
    name: django-migrate-job
    run_command: python manage.py migrate --noinput
    source_dir: /
name: try-django-32-via-cli
region: nyc
services:
  - environment_slug: python
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    github:
      branch: production-3
      deploy_on_push: true
      repo: 20202002karem/first-project
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    name: try-django-3-2
    run_command: gunicorn --worker-tmp-dir /dev/shm main.wsgi
    source_dir: /
