# Generated by Django 3.0 on 2023-01-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num_of_pages', models.ImageField(default=1, upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
