# Generated by Django 4.2.4 on 2023-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeingtegiantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingtegiantimage',
            name='image',
            field=models.ImageField(upload_to='recipes'),
        ),
    ]
