# Generated by Django 4.2.4 on 2023-08-07 08:17

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingtegiantimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recipes.models.recipe_ingrediant_image_upload_handler)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeIngtegiantImage',
        ),
    ]
