name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubutu-latest

    steup:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Collectstatic
        env:
          DEBUG: "0"
          DJANGO_ALLOWED_HOSTS: CI_CD_TEST_KEY
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        run: python manage.py collcetstatic --noinput
