name: CI/CD Django, Postgres,DigitalOcean

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: djtesting
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_ALLOWED_HOSTS: CI_CD_TEST_KEY
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: djtesting
          POSTGRES_PORT: 5432
        run: python manage.py test
      - name: Push Main Branch into Production
        uses: 20202002karem/action-branch-to-branch@main
        with:
          dest_branch: production-3
          source_branch: main
          commit_message: "Release production version"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v3
        with: 
          token: ${{ secrets.DO_ACCESSS_TOKEN }}
      - name: Run a DOCTL command
        run:
        doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yml




        
